name: 'Environment Setup'
description: 'This GitHub Action sets up the testing environment for the project. This allows us to put all steps in one shared composite action.'
runs:
  using: "composite"
  steps:
    - name: Load Bun Cache
      uses: actions/cache@v3
      with:
        path: /root/.bun
        key: ${{ runner.os }}-bun

    - name: Install Bun
      if: steps.cache.outputs.cache-hit != 'true'
      uses: oven-sh/setup-bun@v1

    - name: Load Dependencies Cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      run: bun install
      shell: bash
