name: Code Quality

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  prettier:
    name: Prettier Validation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Prettier Check
        run: bun x prettier --check .
  typescript:
    name: TypeScript Compilation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Compile TypeScript
        run: bun x tsc



